word = ("summer bootcamp")
print(word.title())
print(f"{word[0].upper()}{word[1:14]}{word[-1].upper()} ")
nword = word.replace("b", "L")
print(nword[7:11])
print(f"{word[-4:-1]}{word[4].upper()}")
print(f"{word[12].upper()}{word[5].upper()}")
neww = word.replace(" ", "")
print(neww.isalpha())